POST http://127.0.0.1:5001/parkingapp-af332/us-central1/Register
Content-Type: application/json

{
  "name": "Oussama",
  "surname": "Boussif",
  "email": "abc@gmail.com",
  "phone": "92652461",
  "password": "123456",
  "role": "client"
}

###
POST http://127.0.0.1:5001/parkingapp-af332/us-central1/Login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "123456"
}

###
GET http://127.0.0.1:5001/parkingapp-af332/us-central1/getAllUsers
Content-Type: application/json

###
POST http://127.0.0.1:5001/parkingapp-af332/us-central1/AddDoctor
Content-Type: application/json

{
  "name": "Ahmed",
  "surname": "Boussif",
  "speciality": "Dentist",
  "phone": "92652461",
  "location": "Tunis",
  "email": "mabrouki552@gmail.com",
  "password": "djou123456"
}
###
GET http://127.0.0.1:5001/parkingapp-af332/us-central1/getAllDoctors
Content-Type: application/json
###
POST http://127.0.0.1:5001/parkingapp-af332/us-central1/SetRendezVous
Content-Type: application/json

{
 "doctorId":"ahmedboussif@gmail.com",
 "userId": "abc@gmail.com",
  "date": "2023-05-20",
  "time": "10:00"
}